# Generated by Django 5.0.3 on 2024-06-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topdoc',
            fields=[
                ('did', models.IntegerField(primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=15)),
                ('ddegree', models.CharField(max_length=10)),
                ('dhospital', models.CharField(max_length=20)),
                ('daddress', models.CharField(max_length=30)),
                ('dexprience', models.CharField(max_length=10)),
                ('dspeciality', models.CharField(max_length=20)),
            ],
        ),
    ]
