# Generated by Django 5.0.3 on 2024-06-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topdoc',
            name='dimage',
            field=models.URLField(default='no image'),
        ),
    ]
