# Generated by Django 5.0.3 on 2024-07-10 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='u_name',
            new_name='Uname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='u_password',
            new_name='Upassword',
        ),
    ]
