# Generated by Django 5.0.3 on 2024-07-29 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_users_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
