# Generated by Django 5.0.3 on 2024-07-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('degree', models.CharField(max_length=15)),
                ('speciality', models.CharField(max_length=15)),
                ('hospital', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=40)),
                ('p_count', models.IntegerField()),
            ],
        ),
    ]
