# Generated by Django 5.0.3 on 2025-01-01 06:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_face', models.URLField(default='Empty')),
                ('name', models.CharField(max_length=20)),
                ('degree', models.CharField(max_length=15)),
                ('speciality', models.CharField(max_length=25)),
                ('about', models.CharField(default='Nothing', max_length=175)),
                ('hospital', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=50)),
                ('map_location', models.CharField(default='Empty', max_length=320)),
                ('p_count', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(80), django.core.validators.MinValueValidator(0)])),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('raters_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(null=True)),
                ('P_name', models.CharField(max_length=30)),
                ('P_age', models.IntegerField(default=0)),
                ('P_sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=2)),
                ('state', models.CharField(max_length=25)),
                ('dist', models.CharField(max_length=25)),
                ('appoint_date', models.DateField()),
                ('appoint_time', models.TimeField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('d_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
        ),
    ]
