# Generated by Django 5.0.3 on 2024-07-30 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_alter_doctor_address_alter_doctor_hospital_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('P_name', models.CharField(max_length=30)),
                ('P_age', models.IntegerField()),
                ('state', models.CharField(max_length=25)),
                ('dist', models.CharField(max_length=25)),
                ('appoint_date', models.DateField()),
                ('appoint_time', models.TimeField()),
                ('d_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.doctor')),
            ],
        ),
    ]
